### PR TITLE
Use distro llvm on ubuntu.

### PR DESCRIPTION
**Pull request by dvc94ch**

### CODE REVIEW

**Review by MarijnS95 — APPROVED** [review]
That would work as well and should save time, space and bandwidth, but now we're hit by Dioxus breakage: https://github.com/rust-mobile/xbuild/pull/90#issuecomment-1340689836

**Comment by MarijnS95** [comment]
CI doesn't seem to run at all now, or is it just slow?

**Comment by dvc94ch** [comment]
no idea, looks like github is overloaded

**Comment by dvc94ch** [comment]
looks like it was some kind of race, is running flow on master now

**Comment by MarijnS95** [comment]
Ah so you wanted to merge this straight to master and test the changes there?

**Comment by MarijnS95** [comment]
Looks like it's still failing: https://github.com/rust-mobile/xbuild/actions/runs/3638552687/jobs/6141179175

**Pull request merged**
